import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/artifact/**',
      '**/coverage/**',
      '**/.artifacts/**',
      '**/.vite/**',
      'packages/pix-component-template/src/components/ComponentName/_ComponentName.js',
      'packages/pix-component-template/src/index.types.js',
      'packages/pix-component-template/src/tests/components.test.js',
    ],
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        global: 'readonly',
        globalThis: 'readonly',
        window: 'readonly',
        document: 'readonly',
        getComputedStyle: 'readonly',
        HTMLElement: 'readonly',
        HTMLPreElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        Node: 'readonly',
        NodeFilter: 'readonly',
        Highlight: 'readonly',
        CustomEvent: 'readonly',
        customElements: 'readonly',
        CSSStyleSheet: 'readonly',
        KeyboardEvent: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        queueMicrotask: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        fetch: 'readonly',
        structuredClone: 'readonly',
        URL: 'readonly',
        performance: 'readonly',
        localStorage: 'readonly',
        MediaRecorder: 'readonly',
        Blob: 'readonly',
        AudioContext: 'readonly',
        navigator: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-var': 'error',
      'prefer-const': 'warn',
      'no-console': 'off',
      'no-unused-private-class-members': 'warn',
    },
  },
];
